- src/SocketCore.cc
And also improve tlsHandshake code a bit in the process, mostly by being
more explicit about error conditions.
> Fix SSLv3 warnings being issued on connection reuse.

- src/Context.cc
- src/OptionHandlerFactory.cc
- src/SocketCore.cc
- src/SocketCore.h
- src/prefs.cc
- src/prefs.h
- src/usage_text.h
Code is pretty self explanatory. This adds support for using more than one network interfaces.
```
aria2c --multiple-interface=eth0,eth1 http://url.....
```
> multiple interface support for link aggregation

- Dockerfile.raspberrypi
I would like to add a Dockerfile for cross compilation for armhf
architecture with raspberrypi toolchain.
> Added Dockerfile to cross complile aria2 for RaspberryPI (armhf)

- doc/manual-src/en/mkapiref.py
> Make script compatible with both Python 2 and 3

- doc/manual-src/en/aria2c.rst
WARNING: unknown option: --save-session-file
> Fixed warning

- src/WinConsoleFile.cc
Set default foreground/background colour correctly
> src/WinConsoleFile.cc: fix colour

- AUTHORS
- doc/manual-src/en/aria2c.rst
- src/RpcMethodFactory.cc
- src/RpcMethodFactory.h
- src/RpcMethodImpl.cc
- src/RpcMethodImpl.h
- test/RpcMethodTest.cc
pretty much a copy paste of https://github.com/tatsuhiro-t/aria2/commit/d0ccb39880106984975994d83a858b9f596518a1
related: https://github.com/tatsuhiro-t/aria2/issues/437
> add system.listNotifications RPC method

- doc/manual-src/en/aria2c.rst
for commit 3e00be26e8f8fe44c7344a3e8026031a99b22400
> local IP address to DHT

- Dockerfile.raspberrypi
tar bz2 for expat-x.x.x.tar.bz2
> tar bz2 for expat-x.x.x.tar.bz2

- doc/manual-src/en/aria2c.rst
Hello,
I've reordered one note section in aria2c.rst to match the existing placement of notes after the corresponding options.
Thank you Tatsuhiro, Nils (for deprecated DownThemAll! too) and others for the amazing piece of software!
> Reorder a note section in aria2c.rst

- src/HttpConnection.cc
- src/HttpConnection.h
> Support 1xx non-final response

- src/WinTLSSession.cc
- src/WinTLSSession.h
We re-wrote WinTLSSession::writeData.  The major points are:
* Buffer is now preallocated once handshake is finished.  Previously,
they are allocated each time when we send one TLS record.
* Schannel uses header, body and trailer for each secBuffer.  Now we
send them off at once using WSASend which is windows counterpart of
sendv.  Previously, we do memmove if some of them are truncated.
* We don't try to send application data in
WinTLSSession::closeConnection, since semantically we need same
application data used to create TLS record before.  Using 0 length
data to finish sending buffered data looks like a hack.
> WinTLS: Rewrite writeData

- src/DHTEntryPointNameResolveCommand.cc
- src/DHTEntryPointNameResolveCommand.h
- src/DHTSetup.cc
- src/RequestGroup.cc
> Take into account address family when resolving DHT node address

- src/AbstractDiskWriter.cc
- src/FileAllocationCommand.cc
> Propagate disk full error on pre-allocation to last error code

- src/BtFileAllocationEntry.cc
- src/StreamFileAllocationEntry.cc
> Save control file early

- src/HttpResponse.cc
> Log directed URI in notice log level

- src/SocketCore.cc
> Fix compile error with toolchain which lacks IPV6_TCLASS

- doc/manual-src/en/aria2c.rst
> Clarify --max-concurrent-downloads option

- src/BtFileAllocationEntry.cc
- src/StreamFileAllocationEntry.cc
Don't save control file if --auto-save-interval is 0.
Fixes #917
> Fix regression in bfc54d0b9a694e5d87efd8ed11b5393bc4b66f93

- src/aria2api.cc
> libaria2: Return last error code from DownloadHandle::getErrorCode

- src/WinTLSSession.cc
> wintls: Potential fix for undecrypted read

- src/SelectEventPoll.cc
This commit fixes high CPU usage in BitTorrent downloads.  Only mingw
build is affected by this bug.
Thank you kwkam for identifying the cause of the issue, and helping
debugging this patch.
Fixes #1041, Fixes #1031 
See also #1060
> mingw: Fix high CPU usage in BitTorrent downloads

- src/File.cc
> mingw: Use SetFileTime to avoid DST adjustment

- src/WinTLSSession.cc
> wintls: Don't log writeData error in closing state

- src/DownloadContext.cc
> Don't send Accept Metalink header if Metalink is disabled

- src/GenericParser.h
- src/ValueBaseBencodeParser.h
- src/ValueBaseStructParserStateMachine.cc
- src/ValueBaseStructParserStateMachine.h
- src/XmlRpcRequestParserController.cc
- src/XmlRpcRequestParserController.h
- test/ValueBaseBencodeParserTest.cc
> Allow empty dist name in bencode which is needed for hybrid torrent

- src/WinTLSSession.h
> Add missing <array> include to WinTLSSession.h

- src/DefaultBtProgressInfoFile.cc
Cap infoHashLength in .aria2 file, and save an extra allocation.
> Cap infoHashLength in .aria2 file

- .github/workflows/build.yml
- src/DefaultBtProgressInfoFile.cc
> Fix non bt build error

- src/AsyncNameResolver.cc
- src/AsyncNameResolver.h
- src/SelectEventPoll.cc
- src/SelectEventPoll.h
> Use ares_socket_t where appropriate
