aria2/aria2

- src/SocketCore.cc
`sshSession_` is not defined if libssh2 is not used, so put it after `HAVE_LIBSSH2`
> fix build error without libssh2

- README.rst
- doc/manual-src/en/aria2c.rst
- doc/manual-src/en/technical-notes.rst
- src/OptionHandlerFactory.cc
- src/util.cc
- src/util.h
See http://standards.freedesktop.org/basedir-spec/latest/ for further
details.  This implementation decides the default based on whether a
file exists at the legacy location, if it doesn't, it picks the
XDG-conforming location instead.
> Make config and cache files conform to XDG

- configure.ac
- src/Makefile.am
These commits fix two build issues on MinGW-w64 (using MSYS2, to be precise). I can't guarantee they don't break builds on regular mingw.org or Linux, but hopefully they don't.
Comments welcome.
> Fix build issues with MinGW-w64

- src/AbstractCommand.cc
- src/DownloadResult.h
- src/PeerInteractionCommand.cc
- src/RequestGroup.cc
- src/RequestGroup.h
- src/RequestGroupMan.cc
- src/RpcMethodImpl.cc
I added a new field "errorMessage" to the aria2.tellStatus JSON-RPC response. It provides more information than just the numeric error code. For example, it contains the HTTP error status code returned from the remote server.
> Send the last error message as part of tellStatus RPC response

- Dockerfile.raspberrypi
The RaspberryPi Dockerfile had some out-of-date dependency packages and
was downloading an outdated aria2 source from Sourceforge, which
resulted in a build for version 1.19.0.  The new
fetch-latest-release-from-GitHub script I've cooked up should always
work as long as GitHub doesn't change their API and aria2's platform
agnostic releases follow the "{version number}.tar.bz2" naming format.
> Updated dependency and source url's

- configure.ac
Use m4_ifdef so we do not have to install optional libraries
> configure.ac: fix autoreconf error

- configure.ac
- src/LibgnutlsTLSSession.cc
Hello,
I'm currently maintaining aria2 package for Fedora and EPEL, I carry a small patch to use gnutls system cipher suite as required by packaging guidelines.
I was wondering if you could merge this patch to make updating package easier since it removes the need to rebase the patch every aria2 release.
> Add support for using gnutls system wide crypto policy

- src/CheckIntegrityMan.cc
- src/Makefile.am
- src/RequestGroupEntry.h
- src/RpcMethodImpl.cc
- src/RpcMethodImpl.h
- src/SequentialPicker.h
Allows RPC clients to view progress of the check integrity step.
I didn't notice any tests for TellStatus so I havn't tried to make any for this branch. One other modification I would like to make but wasn't sure how to implement would be reporting if a particular download was in the queue to have its integrity checked (in the CheckIntegrityMan deque). If you had any thoughts on how to do that I'd be happy to implement it.
Please also provide any feedback or changes you like to see made to this PR to be merged.
> Report verifiedLength in tellStatus

- src/AbstractDiskWriter.cc
This has been causing problems with my 32-bit ARMv7L machine. 
It seems like aria2 is compiled with 64-bit offset support so the `filesize` (`st_size` of [`stat`](http://linux.die.net/man/2/stat)) would be a 64-bit `off_t`, even in a 32-bit O/S. 
The problem is, `length` arg in [`mmap`](http://linux.die.net/man/2/mmap) is a 32-bit `size_t` in 32-bit O/S, so the input, `filesize`, would be truncated and the mmap would not be mapping into a correct size of address space.
This will cause `SIGSEGV` in later `memcpy` operations.
> added filesize overflow check for mmap on 32bit os

- src/BtSetup.cc
- src/OptionHandlerFactory.cc
- src/prefs.h
- src/usage_text.h
This allows aria2 to stay up for seeding during seconds and not only full minutes. This is interesting on high speed networks with large number of clients who actually need the file quickly but still want to participate in case all servers need the same file at almost the same time.
> allow seconds for seed-time (fractional minutes)

- src/LpdMessage.cc
- src/LpdMessage.h
- src/LpdMessageDispatcher.cc
- src/LpdMessageDispatcher.h
- src/LpdMessageReceiver.cc
- src/LpdMessageReceiver.h
- src/a2netcompat.h
- src/a2time.h
Append some lines in some files, making the copyright annotation in a consistent format.
>  correcting the copyright format error

- doc/xmlrpc/aria2mon
Hi,
in commit a9fe783484e9196d05b9ea99f441f129365c7034, you already introduced the "secret" parameter to aria2mon. However, in the following call to `aria2.getFiles`, you do not use it, which causes a "Unauthorized (XMLRPC::FaultException)".
Therefore, I replaced the "direct" `client.call` with the local method `client_call` and put the (potential empty) secret as second parameter, so that `clent_call` can either ignore or use it.
> Bugfix: Unauthorized call in aria2mon

- doc/manual-src/en/aria2c.rst
- src/OptionHandlerFactory.cc
- src/OptionHandlerImpl.cc
- src/OptionHandlerImpl.h
The environment variables, such as `${HOME}`, are expanded by shell.
This means that those variables used in configuration file are not
expanded.  However, it is useful to `${HOME}` to refer user's home
directory in configuration file to specify file paths.  Therefore,
aria2 expands `${HOME}` found in the following option values to
user's home directory:
* ca-certificate
* certificate
* dht-file-path
* dht-file-path6
* dir
* input-file
* load-cookies
* log
* metalink-file
* netrc-path
* on-bt-download-complete
* on-download-complete
* on-download-error
* on-download-start
* on-download-stop
* on-download_pause
* out
* private-key
* rpc-certificate
* rpc-private-key
* save-cookies
* save-session
* server-stat-if
* server-stat-of
* torrent-file
Note that this expansion occurs even if the …
> User home variable expansion

- src/BufferedFile.cc
- src/GZipFile.cc
We thought that we can use /dev/stdin for *NIX, but some variants,
like Android, does not have one or root permission is required.  Just
like we do for Windows build, we just use stdin if /dev/stdin is used.
Fixes #785
> Use stdin for *NIX as well

- src/SimpleRandomizer.cc
errno might not be initialized to 0, and we may get both rv == -1 and
errno != ENOSYS.  This leads to assertion failure.  Since
getrandom_linux always returns -1 on failure, checking errno is
useless in this function.
See https://github.com/aria2/aria2/pull/336#issuecomment-270833415
> Fix assertion failure in SimpleRandomizer::getRandomBytes

- src/File.cc
- src/File.h
- src/OptionHandlerImpl.cc
Fixes the misleading error message issue reported in #835.
> Better error message when local file status cannot be retrieved

- Dockerfile.raspberrypi
Some links used in Dockerfile.raspberrypi are not accessible anymore,
because they were pointing to old versions of some source packages and
new versions were released.  This commit fixes this by changing the
links to point to the newest versions.
> Update links in Dockerfile.raspberrypi

- doc/manual-src/en/aria2c.rst
- src/OptionHandlerFactory.cc
- src/download_helper.cc
- src/prefs.cc
- src/prefs.h
- src/usage_text.h
Before getting torrent metadata from DHT when downloading with magnet
link, first try to read file saved by --bt-save-metadata option. If it
is successful, then skip downloading metadata from DHT.  By default,
this feature is turned off.
Fixes #909
> Add --bt-load-saved-metadata option

- doc/manual-src/en/libaria2.rst
aria2::KeyVals is a vector of pair of std strings, therefore the type of object being pushed should be std::pair<std::string, std::string>,
however in the docs, the type of the said object is KeyVals.
If one follows the docs, their code will fail to compile.
> [Docs, libaria2] Fix type of obj pushed into options vector

- doc/manual-src/en/aria2c.rst
- src/Context.cc
- src/DefaultBtInteractive.cc
- src/OptionHandlerFactory.cc
- src/bittorrent_helper.cc
- src/bittorrent_helper.h
- src/prefs.cc
- src/prefs.h
- src/usage_text.h
- test/BittorrentHelperTest.cc
Just hacked this together after reading #901
I modeled this after the --peer-id-prefix settings, is this a good approach for implementing this functionality? Should I model this option after a different option?
Also any suggestions on the name for this setting/parameter I named it since its similar to the "user agent". Maybe "bt-agent", "bt-user-agent", "bt-version", "peer-version", or "bt-extended-version"? Im hesitant to call it  anything with "version" since it is more of an identifier than anything else and may confuse users.
> [WIP] Add option for bt extended handshake version/user agent string

- src/DownloadEngine.cc
This commit fixes the bug that signal handler does not work with
libaria2 when aria2::RUN_ONCE is passed to aria2::run().
> Fix bug that signal handler does not work with libaria2

- src/HttpSkipResponseCommand.cc
HTTP error 502 is returned by reverse proxies when they fail to contact the upstream server. I think aria2 should retry like it does for 503.
> Retry on HTTP 502

- src/util.cc
so if people like to keep FHS they could define XDG_* for it
> util: also detect xdg_* env variables on windows

- src/UnknownLengthPieceStorage.cc
- src/UnknownLengthPieceStorage.h
Can aria2 show completed bytes in terminal while downloading item without Content-Length set?
I found that returning piece length could do it but I am not sure whether it is the proper way.
> UnknownLengthPieceStorage: Completed Length

- src/LibgnutlsTLSSession.cc
> gnutls: Fix bug that commonName is always empty

- src/Platform.cc
Replacing HAVE_SSL should be fine as OPENSSL_VERSION wouldn't be defined either.
> Platform: Fix compilation without deprecated OpenSSL APIs

- doc/manual-src/en/aria2c.rst
- src/AppleTLSSession.cc
- src/LibgnutlsTLSSession.cc
- src/LibsslTLSContext.cc
- src/LibsslTLSSession.cc
- src/OptionHandlerFactory.cc
- src/SocketCore.cc
- src/TLSContext.h
- src/WinTLSContext.cc
- src/WinTLSSession.cc
- src/prefs.cc
- src/prefs.h
- src/util.cc
TLSv1.3 support is added for GNUTLS and OpenSSL.
Fixes #1382 
Closes #1167
> Drop SSLv3.0 and TLSv1.0 and add TLSv1.3

- src/NetStat.cc
This commit resets sessionDownloadLength and sessionUploadLength when
a download restarted (including unpause RPC method).
Fixes #1486
> Reset sessionDownloadLength and sessionUploadLength on download start

- src/AbstractDiskWriter.cc
- src/AbstractDiskWriter.h
- src/AbstractSingleDiskAdaptor.cc
- src/AbstractSingleDiskAdaptor.h
- src/DefaultPieceStorage.cc
- src/DefaultPieceStorage.h
- src/DiskAdaptor.h
- src/DiskWriter.h
- src/MultiDiskAdaptor.cc
- src/MultiDiskAdaptor.h
- src/PieceStorage.h
- src/RequestGroup.cc
- src/UnknownLengthPieceStorage.h
- test/MockPieceStorage.h
*Problem:*
Segments (technically , chunks of in-flight pieces) are marked as finished in the control file (*.aria2) as they are downloaded, though they might not be permanently written, yet, to the storage medium. In the case of app or system crash, and after resuming the download, some segments might have been lost, but the control file marks them as finished.
There is as significant chance for this to happen because of the delay introduced by the in-app disk cache and the OS buffers before the actual physical disk write. By default, auto-save interval is 60 seconds, while, in my case, linux buffer cache had >15s delay and the delay of in-app caches are highly dependent on the download speed because they are flushed once a whole piece completes, which makes it worse for slow network or …
> prevent corrupt downloads after app and/or system crash

- doc/manual-src/en/aria2c.rst
- doc/manual-src/pt/aria2c.rst
- doc/manual-src/ru/aria2c.rst
- src/usage_text.h
Hiya,
I noticed that the docs for `--http-accept-gzip` suggested that aria2c would set the `Accept` header to request a gzip response, rather than the expected `Accept-Encoding`. I thought this was odd, so tested it myself, and I found that the docs are incorrect. In fact aria2c sets the correct header: `Accept-Encoding: deflate, gzip`.
I think these are the only places where it was mentioned incorrectly.
> Fix header in --http-accept-gzip documentation

- src/GZipEncoder.cc
When the output buffer is full, `outbuf[produced]` references past the buffer end, leading to UB and a possible assertion failure.
Fixes #1968, #1964
> Fix undefined behavior/crash in GZipEncoder

- src/MetalinkParserStateV4Impl.cc
Previously, any foreign namespace element inside the root `metalink` element would be handled as if it was the Metalink4 `file` element due to a logic error, essentially breaking the file parsing with a bogus `Specification violation: Missing file@name` error.
> Fix Metalink4 parsing with foreign namespaces

- src/ByteArrayDiskWriter.h
Fixes #1892
Previous limit of 5MB has been set 10 years ago. Meanwhile average computer has at least 3x more memory, see https://techtalk.pcmatic.com/research-charts-memory/. Therefore, let makes this top limit evolves accordingly: up to 15MB.
> Increase ByteArrayDiskWriter maximum size

- README.rst
Fix a typo 'Anroid' --> 'Android', and other minor grammar improvements.
> Minor grammar improvements

- Dockerfile.android
- Dockerfile.mingw
- android-release
- makerelease
- mingw-release
This is slightly different from the current procedure because now android and mingw binaries are built from source code fetched from the remote repository.
> Make releases with docker

- src/AbstractDiskWriter.cc
- src/BitfieldMan.cc
- src/PeerConnection.cc
Use std::copy_n and std::fill_n to avoid a non-nil argument error with memcpy/memset.
> Avoid non-nil argument errors

- src/Logger.cc
This problem occurred on a 32-bit ARM OpenWRT router running Linux 6.1. The method writeHeader() assumes that the size of struct timeval is 8 bytes which is not true on this machine, it is 16 bytes large. Therefore, first cast tv.tv_usec to the unsigned long type.
=========
GDB trace
=========
(gdb) c
Continuing.
Program received signal SIGSEGV, Segmentation fault.
0xb6f4f9b4 in memchr (src=src@entry=0x3b6a, c=c@entry=0x0, n=n@entry=0x7fffffff) at src/string/memchr.c:16
16              for (; ((uintptr_t)s & ALIGN) && n && *s != c; s++, n--);
0xb6f4f98c <memchr+12>:      00 00 52 e3     cmp     r2, #0
0xb6f4f990 <memchr+16>:      00 30 a0 e1     mov     r3, r0
0xb6f4f994 <memchr+20>:      05 00 00 1a     bne     0xb6f4f9b0 <memchr+48>
0xb6f4f998 <memchr+24>:      32 00 00 ea     b …
> Logger: Fix format string overflow in writeHeader()

- doc/manual-src/en/aria2c.rst
- doc/manual-src/pt/aria2c.rst
- src/usage_text.h
- Reword and re-layout `--stream-piece-selector` section in man page (unable to do the same for the Russian man page) -- this mimics the layout from the man page seen in `git help config`.
- Fix 'meta data' --> 'metadata'
- Fix misspelled word 'splited' ('split')
- Reword 2 notes to make them more concise and easier to understand
> Various documenation fixes and rewords 

- Dockerfile.mingw
Downgrade c-ares to 1.19.1 in Dockerfile.mingw because it does not build on x86_64 host.
> Dockerfile.mingw: Downgrade c-ares to 1.19.1

- configure.ac
- src/AsyncNameResolver.cc
- src/AsyncNameResolver.h
- src/AsyncNameResolverMan.cc
- src/AsyncNameResolverMan.h
- src/DownloadEngine.cc
- src/DownloadEngine.h
- src/Event.h
- src/MultiUrlRequestInfo.cc
- src/OptionHandlerFactory.cc
- test/AsyncNameResolverTest.cc
Avoid deprecated functions by newer c-ares.  Now aria2 requires c-ares >= 1.16.0 to get ares_getaddrinfo.
> c-ares: Avoid deprecated functions
